CREATE DATABASE arquiteturapin;

CREATE TABLE usuarios(
	id SERIAL NOT NULL,
	nome VARCHAR(255) NOT NULL,
	login VARCHAR(255) NOT NULL,
	senha VARCHAR(255) NOT NULL,
	CONSTRAINT USUARIOS_ID_PK PRIMARY KEY(id)
);

CREATE TABLE funcionarios(
	id SERIAL NOT NULL,
	nome VARCHAR(255) NOT NULL,
	cpf VARCHAR(11) NOT NULL,
	salario MONEY NOT NULL,
	CONSTRAINT FUNCIONARIOS_ID_PK PRIMARY KEY(id)
);

